git status

echo "Running test cases..."
python test_all.py  # test cases
read

pigar  # evaluate dependencies

read
read -p "Git commit all? ([y]/n): " continue_input


if [[ $continue_input == *"n"* ]]; then
	echo "Not committing..."

else
	echo "Committing all..."
	read -p "Git commit message: " commit_msg_input
	sed -i 's/~xpython ==/wxpython ==/g' requirements.txt  # replace erroneous '~xpython' reference generated by pigar with correct 'wxpython'
	git add .
	git commit -m "$commit_msg_input"
	git push

fi

read -p "Press Enter to exit " # wait for user to press enter before exiting
