echo "Git status:"
git status
read -p "Press Enter to continue..."


printf "\n\n\n\nRunning all test cases..."
python -m unittest discover
read -p "Press Enter to continue..."


printf "\n\n\n\nEvaluating dependencies...\n"
pigar  # evaluate dependencies
read -p "Press Enter to continue..."

printf "\n\n\n\n"
read -p "Git commit all? ([y]/n): " continue_input


if [[ $continue_input == *"n"* ]]; then
	echo "Not committing..."

else
	echo "Committing all..."
	read -p "Git commit message: " commit_msg_input
	sed -i 's/~xpython ==/wxpython ==/g' requirements.txt  # replace erroneous '~xpython' reference generated by pigar with correct 'wxpython'
	git add .
	git commit -m "$commit_msg_input"
	git push

fi

read -p "Press Enter to exit " # wait for user to press enter before exiting
