# initial install of dependencies to setup development environment
pip install pigar
pip install pip-review
pip install pyarmor
pip install pyinstaller
sed -i 's/~xpython ==/wxpython ==/g' requirements.txt  # replace erroneous '~xpython' reference generated by pigar with correct 'wxpython'
pip install -r requirements.txt

read -p "Press Enter to exit" # wait for user to press enter before exiting