# initial install of dependencies to setup development environment
pip install pigar
pip install pip-review
pip install pyarmor
pip install pyinstaller
sed -i 's/~xpython ==/wxpython ==/g' requirements.txt  # replace erroneous '~xpython' reference generated by pigar with correct 'wxpython'
pip install -r requirements.txt

pyarmor register pyarmor-registration.zip  # register pyarmor

# Install singtool to code sign installer
# 1. Download and Windows 10 SDK (just signing tools) from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
# 2. Search for the signtool.exe file across the computer
# 3. Add the file's parent directory to the user path environment variable (to access, search 'edit environement variables')


read -p "Press Enter to exit" # wait for user to press enter before exiting